### PR TITLE
Update Lightkurve to v1.0.1

### PR DESCRIPTION
**Pull request by barentsen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by barentsen** [comment]
@conda-forge-admin, please rerender

**Comment by pkgw** [comment]
I'll merge this, but don't forget that conda-forge has a bot that's pretty good about automatically creating pull requests when new package versions come out on PyPI — see #14. It automatically does the rerender so it can save you that bit of work too. It's pretty fun to do the release and see the PR magically appear!

**Comment by barentsen** [comment]
@pkgw So this is what it feels like to be replaced by a robot?? :sob:  

Haha just kidding, thanks for pointing this out.  Very happy to let our robot friend take care of this in the future! :robot: :smile: :+1:

**Comment by gully** [comment]
Awesome, I'm glad to see that the robot started working after we got to the v1.0.0 milestone, as Peter foretold-- the beta status was hanging-up the robot.

**Pull request merged**
