### PR TITLE
Bump version to v1.0.0 and update requirements

### PR DESCRIPTION
**Pull request by barentsen**
This PR updates the conda package to v1.0.0 and updates the requirements to be consistent with those found in `setup.py`.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pkgw** [comment]
@conda-forge-admin, please rerender.

**Comment by barentsen** [comment]
Oops!  It looks like the build failed because I removed `pytest-runner` as a host requirement.  Pushing cef997b to try this again!

**Comment by barentsen** [comment]
@conda-forge-admin, please rerender.

**Comment by barentsen** [comment]
Looks like the build succeeded now!

@gully do you want to go ahead, merge this PR, and verify in a fresh conda environment that `conda install --channel conda-forge lightkurve` works?  (This is the specific command we advertise on our quickstart.)

**Comment by barentsen** [comment]
Thanks @gully!  Does it work smoothly in a new environment?

**Comment by gully** [comment]
Not yet- there may be some latency between the PR merge and the global conda-forge distribution?

**Comment by gully** [comment]
Voilà! Truncated output confirms `lightkurve` version 1.0.0 is on conda forge: 

```bash
$ conda install --channel conda-forge lightkurve

Collecting package metadata: done
Solving environment: done


The following packages will be downloaded:

   package                    |            build
    ---------------------------|-----------------
    astropy-3.1.2              |   py36h1de35cc_0         6.9 MB  conda-forge
    libtiff-4.0.10             |    h79f4b77_1001         486 KB  conda-forge
    lightkurve-1.0.0           |             py_0         283 KB  conda-forge
    markupsafe-1.1.1           |   py36h1de35cc_0          24 KB  conda-forge

The following NEW packages will be INSTALLED:
  libtiff            conda-forge/osx-64::libtiff-4.0.10-h79f4b77_1001
  lightkurve         conda-forge/noarch::lightkurve-1.0.0-py_0
  markupsafe         conda-forge/osx-64::markupsafe-1.1.1-py36h1de35cc_0

[...]

Downloading and Extracting Packages

pytz-2018.9          | 229 KB    | ##################################### | 100%
lightkurve-1.0.0     | 283 KB    | ##################################### | 100%
pybind11-2.2.4       | 114 KB    | ##################################### | 100%
pyparsing-2.4.0      | 55 KB     | ##################################### | 100%
```

**Comment by barentsen** [comment]
Thanks @gully ! :+1:

**Pull request merged**
